name: Production Deployment

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-20.04

    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Deploy to module a to Production
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
        run: |
          echo "Deploying module a to Production"

      - name: Deploy to module b to Production
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
        run: |
          echo "Deploying module b to Production"

      - name: Deploy to module c to Production
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
        run: |
          echo "Deploying module c to Production"

  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: make tf/init ENV=production

      - name: Terraform Plan
        id: plan
        run: make tf/plan ENV=production

      - name: Deploy to Production
        if: success() && github.ref == 'refs/heads/release'
        run: make tf/apply ENV=production